name: starbucks_app
description: A new Flutter application.

publish_to: 'none'

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  ffi: ^1.1.2

  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  fluttertoast: ^8.0.9
  masked_text_field: ^1.0.0
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:



  uses-material-design: true


  assets:
     - images/sirsalon1.jpg
     - images/sirsalon2.jpg
     - images/sirsalon3.jpg
     - images/sirsalon4.jpg
     - images/sirsalon5.jpg
     - images/sirsalon6.jpg
     - images/sirsalon7.jpg
     - images/sirsalon8.jpg
     - images/sirsalon9.jpg
     - images/sirsalon10.jpg
     - images/sirsalon11.jpg
     - images/sirsalon12.jpg
     - images/sirsalon13.jpg
     - images/sirsalon14.jpg
     - images/sirsalon15.jpg
     - images/sirsalon16.jpg
     - images/promo1.jpg
     - images/promo2.jpg
     - images/logo.jpg
     - images/logo2.png
     - images/SirSalon.jpg
     - images/background1.jpg
     - images/login.jpg


