// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnypr5BZ5_0ZaQOGpnZrUZh_P88B_I9VA',
    appId: '1:892943948631:android:aff7753bbb56e0bc5fbc12',
    messagingSenderId: '892943948631',
    projectId: 'emailpassword-d3e7a',
    storageBucket: 'emailpassword-d3e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXgQeChG_iULcT6fMF5b2Q0RrBd0eHUs',
    appId: '1:892943948631:ios:0c1e03c7766c53275fbc12',
    messagingSenderId: '892943948631',
    projectId: 'emailpassword-d3e7a',
    storageBucket: 'emailpassword-d3e7a.appspot.com',
    iosClientId: '892943948631-fgq7fq39nbdpnp6msncvmakhm3fhhe5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.android',
  );
}